version: "3.9"

services:
  database:
    image: postgres
    container_name: database_insights
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=database_insights
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: backend_insight
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
